name: docs

on:
  push:
    branches:
      - version1
      - version2
  workflow_dispatch:

jobs:
  docs:
    if: github.ref_name != 'main'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build docs
        uses: TinyTapeout/tt-gds-action/docs@ttsky25b
